name: data_state
description: A practical alternative to the AsyncSnapshot API
version: 0.1.0
homepage: https://github.com/flutterdata/data_state
authors:
  - Frank Treacy <me@frank06.net>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  state_notifier: ^0.3.0
  rxdart: ^0.23.1

dev_dependencies:
  build_runner: ^1.8.0
  freezed: ^0.9.2