name: flutter_data_state
description: DataStateBuilder and other data_state Flutter utilities
version: 0.3.6
homepage: https://github.com/flutterdata/data_state/packages/flutter_data_state

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  data_state:
    git:
      url: https://github.com/flutterdata/data_state.git
      path: packages/data_state
      ref: 0.3.6
  flutter_state_notifier: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
