name: data_state
description: A reactive data structure for loading/error/data substates
version: 0.3.1
homepage: https://github.com/flutterdata/data_state

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  state_notifier: ^0.5.0
  async: ^2.4.0
  rxdart: ^0.24.1

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.8.0
  freezed: ^0.10.9