name: data_state
description: A reactive data structure for loading/error/data substates
version: 0.3.5
homepage: https://github.com/flutterdata/data_state

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  freezed_annotation: ^0.11.0
  state_notifier: ^0.6.0

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.8.0
  freezed: ^0.11.2