name: data_state
description: A practical alternative to the AsyncSnapshot API
version: 0.2.7
homepage: https://github.com/flutterdata/data_state

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  state_notifier: ^0.4.0
  rxdart: ^0.24.0
  async: ^2.4.0

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.8.0
  freezed: ^0.10.3